#version 450 core

layout(location = 0) out vec4 outColor;
layout(location = 1) out float outLinearDepth;


in VS_OUT
{
    vec2 patchPositionKm;
    vec3 worldNormal;
}
fsIn;


// =============================================================
// CAMERA / STAR
// =============================================================

uniform vec3 cameraPosition;

uniform vec3 sunDirection;
uniform vec3 sunRadiance;

uniform float sunAngularRadiusRadians;

uniform float timeSeconds;


// =============================================================
// OCEAN MATERIAL
// =============================================================

uniform vec3 deepOceanColor;
uniform vec3 shallowOceanColor;

uniform float oceanRoughness;

uniform float oceanWaveStrength;
uniform float oceanWaveSpeed;


// =============================================================
// TEMPORARY PROCEDURAL COAST OWNERSHIP
// =============================================================

uniform float continentScale;
uniform float detailScale;

uniform float oceanLevel;
uniform float coastWidth;

uniform float planetSeed;


// =============================================================
// LOCAL OCEAN GEOMETRY
// =============================================================

uniform float oceanRadiusKm;

uniform float worldUnitsPerKm;

uniform float geometricWaveVisibility;

uniform vec3 oceanAnchorNormal;
uniform vec3 oceanAnchorRight;
uniform vec3 oceanAnchorForward;
uniform vec3 oceanAnchorRelative;

uniform mat4 planetInverseModel;


// =============================================================
// ATMOSPHERE
// =============================================================

uniform int atmosphereEnabled;

uniform sampler2D atmosphereTransmittanceLut;
uniform sampler2D atmosphereSkyIrradianceLut;
uniform sampler2D atmosphereSkyReflectionLut;

uniform vec3 atmospherePlanetCenterWorld;

uniform float atmosphereKmPerWorldUnit;

uniform float atmosphereBottomRadiusKm;
uniform float atmosphereTopRadiusKm;


// =============================================================
// CONSTANTS
// =============================================================

const float PI =
    3.14159265359;

const float GOLDEN_ANGLE =
    2.39996322973;

const int SUN_DISK_SAMPLE_COUNT =
    12;


// =============================================================
// SMOOTH SEA-LEVEL SURFACE
// =============================================================
//
// IMPORTANT:
//
// The displaced Gerstner geometry is still generated by the
// vertex shader.
//
// This function reconstructs ONLY the underlying smooth spherical
// sea-level surface.
//
// We use this smooth position for view/reflection/atmosphere
// calculations so the individual clipmap triangles cannot leak
// into sharp reflections.
//
// We deliberately do NOT reconstruct the Gerstner displacement in
// this shader.
//

void reconstructSmoothSeaSurface(
    vec2 p,
    out vec3 surfacePosition,
    out vec3 sphereUp,
    out vec3 sphereDirection)
{
    float q =
        dot(
            p,
            p);


    float r =
        sqrt(
            oceanRadiusKm
            *
            oceanRadiusKm
            +
            q);


    float factor =
        oceanRadiusKm
        /
        r;


    sphereUp =
        normalize(
            oceanAnchorNormal
            *
            oceanRadiusKm
            +
            oceanAnchorRight
            *
            p.x
            +
            oceanAnchorForward
            *
            p.y);


    float sag =
        -q
        *
        oceanRadiusKm
        /
        (
            r
            *
            (
                r
                +
                oceanRadiusKm
            )
        );


    vec3 baseOffset =
        oceanAnchorRight
        *
        (
            p.x
            *
            factor
        )
        +
        oceanAnchorForward
        *
        (
            p.y
            *
            factor
        )
        +
        oceanAnchorNormal
        *
        sag;


    surfacePosition =
        cameraPosition
        +
        oceanAnchorRelative
        +
        baseOffset
        *
        worldUnitsPerKm;


    sphereDirection =
        normalize(
            mat3(
                planetInverseModel)
            *
            sphereUp);
}


// =============================================================
// PROCEDURAL COASTLINE NOISE
// =============================================================

float hash31(
    vec3 p)
{
    p =
        fract(
            p
            *
            0.1031);


    p +=
        dot(
            p,
            p.yzx
            +
            33.33);


    return
        fract(
            (
                p.x
                +
                p.y
            )
            *
            p.z);
}


float valueNoise(
    vec3 p)
{
    vec3 cell =
        floor(
            p);


    vec3 f =
        fract(
            p);


    vec3 u =
        f
        *
        f
        *
        (
            3.0
            -
            2.0
            *
            f
        );


    float n000 =
        hash31(
            cell
            +
            vec3(
                0.0,
                0.0,
                0.0));


    float n100 =
        hash31(
            cell
            +
            vec3(
                1.0,
                0.0,
                0.0));


    float n010 =
        hash31(
            cell
            +
            vec3(
                0.0,
                1.0,
                0.0));


    float n110 =
        hash31(
            cell
            +
            vec3(
                1.0,
                1.0,
                0.0));


    float n001 =
        hash31(
            cell
            +
            vec3(
                0.0,
                0.0,
                1.0));


    float n101 =
        hash31(
            cell
            +
            vec3(
                1.0,
                0.0,
                1.0));


    float n011 =
        hash31(
            cell
            +
            vec3(
                0.0,
                1.0,
                1.0));


    float n111 =
        hash31(
            cell
            +
            vec3(
                1.0,
                1.0,
                1.0));


    float nx00 =
        mix(
            n000,
            n100,
            u.x);


    float nx10 =
        mix(
            n010,
            n110,
            u.x);


    float nx01 =
        mix(
            n001,
            n101,
            u.x);


    float nx11 =
        mix(
            n011,
            n111,
            u.x);


    float nxy0 =
        mix(
            nx00,
            nx10,
            u.y);


    float nxy1 =
        mix(
            nx01,
            nx11,
            u.y);


    return
        mix(
            nxy0,
            nxy1,
            u.z);
}


float fbm(
    vec3 p)
{
    float result =
        0.0;


    float amplitude =
        0.5;


    float totalAmplitude =
        0.0;


    for (int octave = 0;
         octave < 5;
         ++octave)
    {
        result +=
            valueNoise(
                p)
            *
            amplitude;


        totalAmplitude +=
            amplitude;


        p =
            p
            *
            2.03
            +
            vec3(
                17.1,
                31.7,
                11.3);


        amplitude *=
            0.5;
    }


    return
        result
        /
        max(
            totalAmplitude,
            0.0001);
}


// =============================================================
// LOCAL MICRO-RIPPLES
// =============================================================
//
// These are unresolved shading ripples only.
//
// The medium/large waves are already represented geometrically by
// ocean_patch.vert.
//

float microHeight(
    vec3 p,
    float footprint)
{
    vec3 drift =
        vec3(
            0.001,
            0.00013,
            0.0004)
        *
        timeSeconds
        *
        oceanWaveSpeed;


    float bandA =
        1.0
        -
        smoothstep(
            0.35,
            1.25,
            footprint
            *
            90.0);


    float bandB =
        1.0
        -
        smoothstep(
            0.35,
            1.25,
            footprint
            *
            240.0);


    return
        bandA
        *
        (
            valueNoise(
                (
                    p
                    +
                    drift
                )
                *
                90.0
                +
                planetSeed)
            -
            0.5
        )
        /
        90.0
        +
        bandB
        *
        0.4
        *
        (
            valueNoise(
                (
                    p
                    -
                    drift
                    *
                    0.7
                )
                *
                240.0
                +
                planetSeed
                *
                2.3)
            -
            0.5
        )
        /
        240.0;
}


vec3 localOceanRipples(
    vec3 geometricNormal,
    vec3 sphereDirection)
{
    vec3 p =
        normalize(
            sphereDirection)
        *
        oceanRadiusKm;


    float footprint = 0.0;

    float h = 0.0008;

    vec3 helper =
        abs(
            sphereDirection.y)
        <
        0.95
            ?
            vec3(
                0.0,
                1.0,
                0.0)
            :
            vec3(
                1.0,
                0.0,
                0.0);


    vec3 tangent =
        normalize(
            cross(
                helper,
                sphereDirection));


    vec3 bitangent =
        cross(
            sphereDirection,
            tangent);


    float dx =
        (
            microHeight(
                p
                +
                tangent
                *
                h,
                footprint)
            -
            microHeight(
                p
                -
                tangent
                *
                h,
                footprint)
        )
        /
        (
            2.0
            *
            h
        );


    float dz =
        (
            microHeight(
                p
                +
                bitangent
                *
                h,
                footprint)
            -
            microHeight(
                p
                -
                bitangent
                *
                h,
                footprint)
        )
        /
        (
            2.0
            *
            h
        );


    vec3 worldTangent =
        normalize(
            transpose(
                mat3(
                    planetInverseModel))
            *
            tangent);


    vec3 worldBitangent =
        normalize(
            transpose(
                mat3(
                    planetInverseModel))
            *
            bitangent);


    float rippleStrength =
        0.085
        *
        clamp(
            oceanWaveStrength
            /
            0.18,
            0.0,
            3.0)
        *
        geometricWaveVisibility;


    return
        normalize(
            geometricNormal
            -
            (
                worldTangent
                *
                dx
                +
                worldBitangent
                *
                dz
            )
            *
            rippleStrength);
}


float oceanFacetVariation(
    vec3 geometricNormal,
    vec3 waveNormal,
    vec3 viewDirection)
{
    float geometricFacing =
        clamp(
            dot(
                geometricNormal,
                viewDirection),
            0.0,
            1.0);


    float waveFacing =
        clamp(
            dot(
                waveNormal,
                viewDirection),
            0.0,
            1.0);


    return
        clamp(
            (
                waveFacing
                -
                geometricFacing
            )
            *
            2.5,
            -0.10,
            0.10);
}


// =============================================================
// GGX
// =============================================================

float distributionGGX(
    vec3 N,
    vec3 H,
    float materialRoughness)
{
    float a =
        materialRoughness
        *
        materialRoughness;


    float a2 =
        a
        *
        a;


    float NdotH =
        max(
            dot(
                N,
                H),
            0.0);


    float NdotH2 =
        NdotH
        *
        NdotH;


    float denominator =
        NdotH2
        *
        (
            a2
            -
            1.0
        )
        +
        1.0;


    denominator =
        PI
        *
        denominator
        *
        denominator;


    return
        a2
        /
        max(
            denominator,
            0.000001);
}


float geometrySchlickGGX(
    float NdotV,
    float materialRoughness)
{
    float r =
        materialRoughness
        +
        1.0;


    float k =
        (
            r
            *
            r
        )
        /
        8.0;


    return
        NdotV
        /
        max(
            NdotV
            *
            (
                1.0
                -
                k
            )
            +
            k,
            0.000001);
}


float geometrySmith(
    vec3 N,
    vec3 V,
    vec3 L,
    float materialRoughness)
{
    return
        geometrySchlickGGX(
            max(
                dot(
                    N,
                    V),
                0.0),
            materialRoughness)
        *
        geometrySchlickGGX(
            max(
                dot(
                    N,
                    L),
                0.0),
            materialRoughness);
}


vec3 fresnelSchlick(
    float cosTheta,
    vec3 F0)
{
    return
        F0
        +
        (
            vec3(
                1.0)
            -
            F0
        )
        *
        pow(
            1.0
            -
            cosTheta,
            5.0);
}


vec3 evaluateDirectionalSpecular(
    vec3 N,
    vec3 V,
    vec3 L,
    vec3 F0,
    float materialRoughness)
{
    float NdotL =
        max(
            dot(
                N,
                L),
            0.0);


    float NdotV =
        max(
            dot(
                N,
                V),
            0.0);


    if (NdotL <=
            0.0
        ||
        NdotV <=
            0.0)
    {
        return
            vec3(
                0.0);
    }


    vec3 H =
        normalize(
            V
            +
            L);


    float NDF =
        distributionGGX(
            N,
            H,
            materialRoughness);


    float G =
        geometrySmith(
            N,
            V,
            L,
            materialRoughness);


    vec3 F =
        fresnelSchlick(
            max(
                dot(
                    H,
                    V),
                0.0),
            F0);


    vec3 specular =
        (
            NDF
            *
            G
            *
            F
        )
        /
        max(
            4.0
            *
            NdotV
            *
            NdotL,
            0.0001);


    return
        specular
        *
        NdotL;
}


// =============================================================
// FINITE STELLAR DISK
// =============================================================

void buildStarBasis(
    vec3 centerDirection,
    out vec3 tangent,
    out vec3 bitangent)
{
    vec3 helper =
        abs(
            centerDirection.y)
        <
        0.95
            ?
            vec3(
                0.0,
                1.0,
                0.0)
            :
            vec3(
                1.0,
                0.0,
                0.0);


    tangent =
        normalize(
            cross(
                helper,
                centerDirection));


    bitangent =
        normalize(
            cross(
                centerDirection,
                tangent));
}


vec3 stellarDiskDirection(
    vec3 centerDirection,
    vec3 tangent,
    vec3 bitangent,
    float diskRadius,
    float azimuth)
{
    float cosTheta =
        cos(
            diskRadius);


    float sinTheta =
        sin(
            diskRadius);


    vec3 radialDirection =
        tangent
        *
        cos(
            azimuth)
        +
        bitangent
        *
        sin(
            azimuth);


    return
        normalize(
            centerDirection
            *
            cosTheta
            +
            radialDirection
            *
            sinTheta);
}


vec3 finiteStarSpecular(
    vec3 N,
    vec3 V,
    vec3 centerLightDirection,
    vec3 F0,
    float materialRoughness)
{
    if (sunAngularRadiusRadians <=
        0.000001)
    {
        return
            evaluateDirectionalSpecular(
                N,
                V,
                centerLightDirection,
                F0,
                materialRoughness);
    }


    vec3 tangent;

    vec3 bitangent;


    buildStarBasis(
        centerLightDirection,
        tangent,
        bitangent);


    vec3 accumulatedSpecular =
        vec3(
            0.0);


    for (int sampleIndex = 0;
         sampleIndex < SUN_DISK_SAMPLE_COUNT;
         ++sampleIndex)
    {
        float u =
            (
                float(
                    sampleIndex)
                +
                0.5
            )
            /
            float(
                SUN_DISK_SAMPLE_COUNT);


        float radialFraction =
            sqrt(
                u);


        float angularRadius =
            sunAngularRadiusRadians
            *
            radialFraction;


        float azimuth =
            float(
                sampleIndex)
            *
            GOLDEN_ANGLE;


        vec3 sampleDirection =
            stellarDiskDirection(
                centerLightDirection,
                tangent,
                bitangent,
                angularRadius,
                azimuth);


        accumulatedSpecular +=
            evaluateDirectionalSpecular(
                N,
                V,
                sampleDirection,
                F0,
                materialRoughness);
    }


    return
        accumulatedSpecular
        /
        float(
            SUN_DISK_SAMPLE_COUNT);
}


// =============================================================
// ATMOSPHERE GROUND INTERSECTION
// =============================================================

bool atmosphereRayHitsGround(
    vec3 positionKm,
    vec3 direction)
{
    vec3 position =
        positionKm
        /
        atmosphereBottomRadiusKm;


    float b =
        dot(
            position,
            direction);


    float c =
        dot(
            position,
            position)
        -
        1.0;


    float discriminant =
        b
        *
        b
        -
        c;


    if (discriminant <
        0.0)
    {
        return
            false;
    }


    float nearest =
        -b
        -
        sqrt(
            max(
                discriminant,
                0.0));


    return
        nearest
        >
        0.000001;
}


// =============================================================
// DIRECT STAR TRANSMITTANCE
// =============================================================

vec2 atmosphereTransmittanceUv(
    vec3 positionKm,
    vec3 direction)
{
    float radius =
        length(
            positionKm);


    vec3 localUp =
        positionKm
        /
        radius;


    float mu =
        clamp(
            dot(
                localUp,
                direction),
            -1.0,
            1.0);


    float H =
        sqrt(
            max(
                atmosphereTopRadiusKm
                *
                atmosphereTopRadiusKm
                -
                atmosphereBottomRadiusKm
                *
                atmosphereBottomRadiusKm,
                0.0));


    float rho =
        sqrt(
            max(
                radius
                *
                radius
                -
                atmosphereBottomRadiusKm
                *
                atmosphereBottomRadiusKm,
                0.0));


    float discriminant =
        radius
        *
        radius
        *
        (
            mu
            *
            mu
            -
            1.0
        )
        +
        atmosphereTopRadiusKm
        *
        atmosphereTopRadiusKm;


    float distanceToTop =
        -radius
        *
        mu
        +
        sqrt(
            max(
                discriminant,
                0.0));


    float distanceMinimum =
        atmosphereTopRadiusKm
        -
        radius;


    float distanceMaximum =
        rho
        +
        H;


    float xMu =
        (
            distanceToTop
            -
            distanceMinimum
        )
        /
        max(
            distanceMaximum
            -
            distanceMinimum,
            0.000001);


    float xRadius =
        rho
        /
        max(
            H,
            0.000001);


    vec2 parameterUv =
        clamp(
            vec2(
                xMu,
                xRadius),
            vec2(
                0.0),
            vec2(
                1.0));


    vec2 size =
        vec2(
            textureSize(
                atmosphereTransmittanceLut,
                0));


    return
        (
            parameterUv
            *
            (
                size
                -
                vec2(
                    1.0)
            )
            +
            vec2(
                0.5)
        )
        /
        size;
}


vec3 atmosphereSunTransmittance(
    vec3 worldPosition,
    vec3 directionToSun)
{
    if (atmosphereEnabled ==
        0)
    {
        return
            vec3(
                1.0);
    }


    vec3 positionKm =
        (
            worldPosition
            -
            atmospherePlanetCenterWorld
        )
        *
        atmosphereKmPerWorldUnit;


    float radiusKm =
        length(
            positionKm);


    if (radiusKm <=
        0.000001)
    {
        return
            vec3(
                1.0);
    }


    vec3 localUp =
        positionKm
        /
        radiusKm;


    radiusKm =
        max(
            radiusKm,
            atmosphereBottomRadiusKm
            +
            0.001);


    positionKm =
        localUp
        *
        radiusKm;


    if (atmosphereRayHitsGround(
            positionKm,
            directionToSun))
    {
        return
            vec3(
                0.0);
    }


    return
        textureLod(
            atmosphereTransmittanceLut,
            atmosphereTransmittanceUv(
                positionKm,
                directionToSun),
            0.0).rgb;
}


// =============================================================
// DIFFUSE ATMOSPHERIC SKY IRRADIANCE
// =============================================================

vec2 atmosphereSkyIrradianceUv(
    float altitudeKm,
    float sunMu)
{
    float atmosphereThicknessKm =
        atmosphereTopRadiusKm
        -
        atmosphereBottomRadiusKm;


    float encodedSunMu =
        sign(
            sunMu)
        *
        sqrt(
            abs(
                sunMu));


    float u =
        encodedSunMu
        *
        0.5
        +
        0.5;


    float altitudeFraction =
        clamp(
            altitudeKm
            /
            max(
                atmosphereThicknessKm,
                0.000001),
            0.0,
            1.0);


    float v =
        sqrt(
            altitudeFraction);


    vec2 parameterUv =
        clamp(
            vec2(
                u,
                v),
            vec2(
                0.0),
            vec2(
                1.0));


    vec2 size =
        vec2(
            textureSize(
                atmosphereSkyIrradianceLut,
                0));


    return
        (
            parameterUv
            *
            (
                size
                -
                vec2(
                    1.0)
            )
            +
            vec2(
                0.5)
        )
        /
        size;
}


vec3 atmosphereSkyIrradiance(
    vec3 worldPosition,
    vec3 surfaceUp,
    vec3 directionToSun,
    out vec3 localUp)
{
    localUp =
        surfaceUp;


    if (atmosphereEnabled ==
        0)
    {
        return
            vec3(
                0.0);
    }


    vec3 positionKm =
        (
            worldPosition
            -
            atmospherePlanetCenterWorld
        )
        *
        atmosphereKmPerWorldUnit;


    float radiusKm =
        length(
            positionKm);


    if (radiusKm <=
        0.000001)
    {
        return
            vec3(
                0.0);
    }


    localUp =
        positionKm
        /
        radiusKm;


    float altitudeKm =
        clamp(
            radiusKm
            -
            atmosphereBottomRadiusKm,
            0.0,
            atmosphereTopRadiusKm
            -
            atmosphereBottomRadiusKm);


    float sunMu =
        clamp(
            dot(
                localUp,
                directionToSun),
            -1.0,
            1.0);


    return
        textureLod(
            atmosphereSkyIrradianceLut,
            atmosphereSkyIrradianceUv(
                altitudeKm,
                sunMu),
            0.0).rgb;
}


// =============================================================
// SKY-REFLECTION LUT DIRECTION MAPPING
// =============================================================

vec2 atmosphereUnitUvToSubUv(
    vec2 uv,
    vec2 textureSizePixels)
{
    return
        (
            clamp(
                uv,
                vec2(
                    0.0),
                vec2(
                    1.0))
            *
            (
                textureSizePixels
                -
                vec2(
                    1.0)
            )
            +
            vec2(
                0.5)
        )
        /
        textureSizePixels;
}


vec2 atmosphereSkyViewUv(
    vec3 rayDirection,
    vec3 probeRelativeWorld)
{
    vec3 localUp =
        normalize(
            probeRelativeWorld);


    float viewHeightKm =
        max(
            length(
                probeRelativeWorld)
            *
            atmosphereKmPerWorldUnit,
            atmosphereBottomRadiusKm
            +
            0.001);


    float viewZenithCosAngle =
        clamp(
            dot(
                rayDirection,
                localUp),
            -1.0,
            1.0);


    vec3 normalizedSunDirection =
        normalize(
            sunDirection);


    vec3 sunTangent =
        normalizedSunDirection
        -
        localUp
        *
        dot(
            normalizedSunDirection,
            localUp);


    float sunTangentLength =
        length(
            sunTangent);


    if (sunTangentLength <
        0.000001)
    {
        vec3 reference =
            abs(
                localUp.y)
            <
            0.99
                ?
                vec3(
                    0.0,
                    1.0,
                    0.0)
                :
                vec3(
                    1.0,
                    0.0,
                    0.0);


        sunTangent =
            normalize(
                cross(
                    reference,
                    localUp));
    }
    else
    {
        sunTangent /=
            sunTangentLength;
    }


    float viewZenithSinAngle =
        sqrt(
            max(
                1.0
                -
                viewZenithCosAngle
                *
                viewZenithCosAngle,
                0.0));


    float lightViewCosAngle =
        1.0;


    if (viewZenithSinAngle >
        0.000001)
    {
        vec3 viewTangent =
            (
                rayDirection
                -
                localUp
                *
                viewZenithCosAngle
            )
            /
            viewZenithSinAngle;


        lightViewCosAngle =
            clamp(
                dot(
                    viewTangent,
                    sunTangent),
                -1.0,
                1.0);
    }


    float horizonDistance =
        sqrt(
            max(
                viewHeightKm
                *
                viewHeightKm
                -
                atmosphereBottomRadiusKm
                *
                atmosphereBottomRadiusKm,
                0.0));


    float cosBeta =
        clamp(
            horizonDistance
            /
            max(
                viewHeightKm,
                0.000001),
            0.0,
            1.0);


    float beta =
        acos(
            cosBeta);


    float zenithHorizonAngle =
        PI
        -
        beta;


    float viewZenithAngle =
        acos(
            viewZenithCosAngle);


    vec2 uv;


    if (viewZenithAngle <=
        zenithHorizonAngle)
    {
        float coord =
            viewZenithAngle
            /
            max(
                zenithHorizonAngle,
                0.000001);


        coord =
            clamp(
                coord,
                0.0,
                1.0);


        coord =
            1.0
            -
            coord;


        coord =
            sqrt(
                max(
                    coord,
                    0.0));


        coord =
            1.0
            -
            coord;


        uv.y =
            coord
            *
            0.5;
    }
    else
    {
        float coord =
            (
                viewZenithAngle
                -
                zenithHorizonAngle
            )
            /
            max(
                beta,
                0.000001);


        coord =
            clamp(
                coord,
                0.0,
                1.0);


        coord =
            sqrt(
                coord);


        uv.y =
            coord
            *
            0.5
            +
            0.5;
    }


    float azimuthCoord =
        -lightViewCosAngle
        *
        0.5
        +
        0.5;


    azimuthCoord =
        sqrt(
            clamp(
                azimuthCoord,
                0.0,
                1.0));


    uv.x =
        azimuthCoord;


    return
        atmosphereUnitUvToSubUv(
            uv,
            vec2(
                textureSize(
                    atmosphereSkyReflectionLut,
                    0)));
}


// =============================================================
// HORIZON-STABLE REFLECTION
// =============================================================

vec3 makeHorizonSafeReflectionDirection(
    vec3 rawDirection,
    vec3 smoothUp,
    out float skyReflectionWeight)
{
    float rawMu =
        clamp(
            dot(
                rawDirection,
                smoothUp),
            -1.0,
            1.0);


    skyReflectionWeight =
        smoothstep(
            -0.08,
            0.05,
            rawMu);


    vec3 tangent =
        rawDirection
        -
        smoothUp
        *
        rawMu;


    float tangentLengthSquared =
        dot(
            tangent,
            tangent);


    if (tangentLengthSquared <
        0.000001)
    {
        vec3 helper =
            abs(
                smoothUp.y)
            <
            0.95
                ?
                vec3(
                    0.0,
                    1.0,
                    0.0)
                :
                vec3(
                    1.0,
                    0.0,
                    0.0);


        tangent =
            normalize(
                cross(
                    helper,
                    smoothUp));
    }
    else
    {
        tangent *=
            inversesqrt(
                tangentLengthSquared);
    }


    const float minimumUpComponent =
        0.02;


    const float tangentComponent =
        sqrt(
            max(
                1.0
                -
                minimumUpComponent
                *
                minimumUpComponent,
                0.0));


    vec3 horizonSafeDirection =
        normalize(
            tangent
            *
            tangentComponent
            +
            smoothUp
            *
            minimumUpComponent);


    float useRawDirection =
        smoothstep(
            0.02,
            0.10,
            rawMu);


    return
        normalize(
            mix(
                horizonSafeDirection,
                rawDirection,
                useRawDirection));
}


// =============================================================
// PREFILTERED ATMOSPHERIC REFLECTION
// =============================================================

vec3 atmospherePrefilteredSkyReflection(
    vec3 reflectionDirection,
    float materialRoughness)
{
    if (atmosphereEnabled ==
        0)
    {
        return
            vec3(
                0.0);
    }


    vec3 probeRelativeWorld =
        cameraPosition
        -
        atmospherePlanetCenterWorld;


    if (length(
            probeRelativeWorld)
        <=
        0.000001)
    {
        return
            vec3(
                0.0);
    }


    vec2 skyUv =
        atmosphereSkyViewUv(
            reflectionDirection,
            probeRelativeWorld);


    float maxMip =
        float(
            textureQueryLevels(
                atmosphereSkyReflectionLut)
            -
            1);


    float mipLevel =
        clamp(
            materialRoughness
            *
            maxMip,
            0.0,
            maxMip);


    return
        textureLod(
            atmosphereSkyReflectionLut,
            skyUv,
            mipLevel).rgb;
}


// =============================================================
// MAIN
// =============================================================

void main()
{
    // Smooth analytic sea-level position.
    //
    // This removes the clipmap triangle pattern from position-
    // sensitive reflection calculations without duplicating the
    // expensive Gerstner wave evaluation per fragment.
    vec3 surfacePosition;

    vec3 sphereUp;

    vec3 sphereDirection;


    reconstructSmoothSeaSurface(
        fsIn.patchPositionKm,
        surfacePosition,
        sphereUp,
        sphereDirection);


    // Gerstner normal supplied by the vertex shader.
    vec3 geometricNormal =
        normalize(
            fsIn.worldNormal);


    vec3 V =
        normalize(
            cameraPosition
            -
            surfacePosition);


    vec3 centerLightDirection =
        normalize(
            sunDirection);


    // =========================================================
    // TEMPORARY PROCEDURAL LAND / OCEAN OWNERSHIP
    // =========================================================

    vec3 seedOffset =
        vec3(
            planetSeed
            *
            1.371,

            planetSeed
            *
            2.113,

            planetSeed
            *
            3.731);


    float continents =
        fbm(
            sphereDirection
            *
            continentScale
            +
            seedOffset);


    float detail =
        fbm(
            sphereDirection
            *
            detailScale
            +
            seedOffset
            *
            2.7);


    float height =
        continents
        *
        0.82
        +
        detail
        *
        0.18;


    float landMask =
        smoothstep(
            oceanLevel
            -
            coastWidth,

            oceanLevel
            +
            coastWidth,

            height);


    if (landMask >=
        0.5)
    {
        discard;
    }


    // =========================================================
    // OCEAN COLOR
    // =========================================================

    float shallowFactor =
        smoothstep(
            oceanLevel
            -
            0.10,

            oceanLevel,

            height);


    vec3 oceanColor =
        mix(
            deepOceanColor,
            shallowOceanColor,
            shallowFactor);


    // =========================================================
    // GERSTNER NORMAL + MICRO RIPPLE NORMAL
    // =========================================================

    vec3 resolvedOceanNormal =
        localOceanRipples(
            geometricNormal,
            sphereDirection);


    vec3 smoothRippleNormal =
        localOceanRipples(
            sphereUp,
            sphereDirection);
            
    vec3 reflectionOceanNormal =
        normalize(
            mix(
                sphereUp,
                smoothRippleNormal,
                0.35));
    vec3 glitterNormal =
        normalize(
            mix(
                sphereUp,
                smoothRippleNormal,
                0.12));


    float facetVariation =
        oceanFacetVariation(
            geometricNormal,
            reflectionOceanNormal,
            V);


    vec3 waterBodyColor =
        oceanColor
        *
        (
            1.0
            +
            facetVariation
        );


    // =========================================================
    // MATERIAL ROUGHNESS
    // =========================================================

    float normalDeviation =
        clamp(
            1.0
            -
            dot(
                geometricNormal,
                resolvedOceanNormal),
            0.0,
            1.0);


    float materialRoughness =
        clamp(
            oceanRoughness
            +
            normalDeviation
            *
            0.30,
            0.035,
            0.22);


    float diffuseStrength =
        0.016;


    vec3 F0 =
        vec3(
            0.022);


    // =========================================================
    // DIRECT STAR DIFFUSE
    // =========================================================

    float centerNdotL =
        max(
            dot(
                geometricNormal,
                centerLightDirection),
            0.0);


    vec3 centerHalf =
        normalize(
            V
            +
            centerLightDirection);


    vec3 centerFresnel =
        fresnelSchlick(
            max(
                dot(
                    centerHalf,
                    V),
                0.0),
            F0);


    vec3 diffuseBrdf =
        (
            vec3(
                1.0)
            -
            centerFresnel
        )
        *
        waterBodyColor
        *
        diffuseStrength
        /
        PI;


    vec3 sunlight =
        sunRadiance
        *
        atmosphereSunTransmittance(
            surfacePosition,
            centerLightDirection);


    vec3 directDiffuse =
        diffuseBrdf
        *
        sunlight
        *
        centerNdotL;


    // =========================================================
    // DIRECT FINITE-STAR SPECULAR
    // =========================================================

    vec3 directSpecular =
        finiteStarSpecular(
            glitterNormal,
            V,
            centerLightDirection,
            F0,
            materialRoughness)
        *
        sunlight;


    // =========================================================
    // DIFFUSE ATMOSPHERIC SKY LIGHT
    // =========================================================

    vec3 localUp;


    vec3 skyResponse =
        atmosphereSkyIrradiance(
            surfacePosition,
            sphereUp,
            centerLightDirection,
            localUp);


    vec3 skyIrradiance =
        skyResponse
        *
        sunRadiance;


    float skyVisibility =
        clamp(
            0.5
            +
            0.5
            *
            dot(
                geometricNormal,
                localUp),
            0.0,
            1.0);


    vec3 skyDiffuse =
        waterBodyColor
        *
        diffuseStrength
        *
        skyIrradiance
        *
        skyVisibility
        /
        PI;


    // =========================================================
    // PREFILTERED ATMOSPHERIC SKY REFLECTION
    // =========================================================

    vec3 rawReflectedSkyDirection =
        normalize(
            reflect(
                -V,
                reflectionOceanNormal));


    float skyReflectionWeight;


    vec3 safeReflectedSkyDirection =
        makeHorizonSafeReflectionDirection(
            rawReflectedSkyDirection,
            sphereUp,
            skyReflectionWeight);


    vec3 localSkyRadiance =
        atmospherePrefilteredSkyReflection(
            safeReflectedSkyDirection,
            materialRoughness);


    vec3 neighboringSurfaceFallback =
        skyIrradiance
        *
        (
            0.16
            /
            PI
        );


    vec3 reflectedEnvironmentRadiance =
        mix(
            neighboringSurfaceFallback,
            localSkyRadiance,
            skyReflectionWeight);


    // =========================================================
    // WATER FRESNEL
    // =========================================================

    float oceanNdotV =
        max(
            dot(
                reflectionOceanNormal,
                V),
            0.0);


    vec3 oceanFresnel =
        fresnelSchlick(
            oceanNdotV,
            vec3(
                0.02));


    vec3 oceanSkyReflection =
        reflectedEnvironmentRadiance
        *
        oceanFresnel;


    // =========================================================
    // FINAL SURFACE RADIANCE
    // =========================================================

    vec3 finalColor =
        directDiffuse
        +
        directSpecular
        +
        skyDiffuse
        +
        oceanSkyReflection;


    outColor =
        vec4(
            finalColor,
            1.0);


    // Deliberately use the smooth sea-level position here.
    //
    // Wave displacement is only a few metres, while this prevents
    // the atmosphere composite from seeing the clipmap's individual
    // triangle interpolation.
    outLinearDepth =
        length(
            cameraPosition
            -
            surfacePosition);
}