#pragma once

#include "renderer/RenderCamera.h"

#include "renderer/atmosphere/AtmosphereInstance.h"
#include "renderer/atmosphere/AtmosphereViewLuts.h"

#include "renderer/lighting/DirectionalLight.h"

#include "renderer/opengl/GlShader.h"

#include <glad/gl.h>


namespace SpaceSim
{
    class AtmospherePass
    {
    public:
        AtmospherePass();

        ~AtmospherePass();


        AtmospherePass(
            const AtmospherePass&) = delete;


        AtmospherePass& operator=(
            const AtmospherePass&) = delete;


        // Composites atmosphere over an already-rendered HDR scene.
        //
        // AtmosphereViewLuts are generated by SceneRenderer before
        // geometry rendering so both PBR and this pass can share
        // the exact same atmospheric view data.

        GLuint render(
            int width,
            int height,
            GLuint sceneColorTexture,
            GLuint sceneLinearDepthTexture,
            const RenderCamera& camera,
            float aspectRatio,
            const DirectionalLight& sun,
            const AtmosphereInstance& atmosphere,
            const AtmosphereViewLuts& viewLuts);


    private:
        void resize(
            int width,
            int height);


        void destroyTarget();


        GlShader m_shader;


        GLuint m_vertexArray =
            0;


        GLuint m_framebuffer =
            0;


        GLuint m_colorTexture =
            0;


        int m_width =
            0;


        int m_height =
            0;
    };
}